export const AllFeatureData = {
  featureList1: [
    "VITA-62 Compliant",
    "28VDC Nominal I/P",
    "18 to 36 VDC Range",
    "MIL-STD-704 (A-F) Normal and Abnormal Steady State",
    "MIL-STD-704(A-F) transients Up to 50V, 80V",
    "MIL-STD-704(A-F) Transients Under 18V and Starting transients",
    " 3U 4HP 1 Form Factor",
    "  DC Wide Input Range",
    "Standard 6 outputs",
    "I2C™ monitoring and control",
    " Conduction cooled",
    " 400W O/P Power(continuous)",
    "Monitoring all input/output voltages, currents and power",
    " Current fold back control",
    " Enable, inhibit, system reset and power fail controls",
    "  Remote voltage sense: VS1, VS2, VS3",
    "  Build to meet Military Standards MIL STD 704F, MIL STD 461F, MIL STD 810G",
  ],
  featureList_C1: [
    "VITA-62 Compliant",
    "28VDC Nominal I/P",
    "18 to 36 VDC Range",
    "MIL-STD-704 (A-F) Normal and Abnormal Steady State",
    "MIL-STD-704(A-F) transients Up to 50V, 80V",
    "MIL-STD-704(A-F) Transients Under 18V and Starting transients",
    " 3U 4HP 1 Form Factor",
    "  DC Wide Input Range",
    "Standard 6 outputs",
    "I2C™ monitoring and control",
    " Conduction cooled",
    " 400W O/P Power(continuous)",
    "Monitoring all input/output voltages, currents and power",
    " Current fold back control",
    " Enable, inhibit, system reset and power fail controls",
    "  Remote voltage sense: VS1, VS2, VS3",
    "  Build to meet Military Standards MIL STD 704F, MIL STD 461F, MIL STD 810G",
  ],
  // -------------backplane--------------
  featureList_BP1: [
    "Compliant to VITA 46.0 Baseline Application",
    "Supports VITA 46.4 x1 PCI Express® Gen3",
    "Supports VITA 65 including Ethernet 10G BASE-KR",
    " slot 3U VPX Backplane 1” slot pitch",
    "VITA 42 standard PSU slot",
    "Utility Plane includes power",
    "Custom connectors for 1G-Ethernets, USB, RS232, RS422 and other discrete IOs on back plane",
    "Uses the rugged 3U Eurocard form factor standard with the EPT Velox connector",
    "Two PCIe x 4 (Fat Pipe) host to 3rd Slot for Graphics Processor",
    "JTAG interface & geographic address pins",
    "Provides built in ESD ground protection in every slot",
    "Support for Intelligent Platform Management Interface (IPMI)",
    "M3 studs for power entry",
    "Flexible keying and alignment mechanism",
  ],

  featureList_BP2: [
    "Conforms to VME64 specification (ANSI/VITA 1-1994)",
    "True 3U/6U eurocard height",
    "Excellent crosstalk performance, low ground shift",
    "Automatic daisy chain of BG/IACK signals (mechanical or electronic) On-board, passive termination",
    "Latchable service header for system reset, AC fail & system fail signals (Contact us for connector details and pinning)",
    "Power on via M4 screw / 6.35mm faston tab (busbars available on request for larger slot sizes)",
    "Extended tails with shrouds on all J2 connectors",
    "Conductive surface area top and bottom (chassis GND) for EMC-tight seal between backplane and subrack",
    "High frequency coupling capacitors (10nF, 200V) in each slot",
  ],
  featureList_BP3: [
    "Conforms to VME64x specification (ANSI/VITA 1.1-1997)",
    "Fits within a 6U Eurocard",
    "Available in 01-21 slot widths",
    "Surface mount, active termination",
    "Electronic, on-board, automatic daisy chain (BG/IACK signals)",
    "Power connections via busbars (M6 screws) and power studs (M3)",
    "Decoupling capacitors in every slot",
    "All P2 connectors long tail / gold-plated",
    "With or without P0 connectors",
  ],
  featureList_BP4: [
    "Compliant to the latest VITA 41 Standards",
    "Various slot widths",
    "6U standard Eurocard formfactor",
    "Hybrid versions available",
    "High speed, multi-gig connector",
    "High performance, low noise",
  ],
  featureList_BP5: [
    "Compliant to the latest VITA 41 Standards",
    "Various slot widths",
    "6U standard Eurocard formfactor",
    "Hybrid versions available",
    "High speed, multi-gig connector",
    "High performance, low noise",
  ],
  featureList_BP6: [
    "Compliant to VITA 46.0 baseline specification",
    "OPEN VITA 65 Specification",
    "Backplane Profile: BKP3-CEN03-15.2.9-n",
    "Customize Slots VPX, 1 Payload Slot, 2 Peripheral Slots",
    "M3 studs power entry",
    "Reference clock",
    "Aux clock",
    "System Management Interface (I2CA, I2CB)",
    "Input current per backplane: VS1 = 28A, VS2 = 28A, VS3 = 30A",
  ],
  // featureList_BP7: [
  // ],
  // -------------rader computer--------------
  featureList_RCA1: [
    "Compact design",
    "2 Nos of Xeon-Based Single Board Computer",
    "Embedded with sFPDP card used for signal processing",
    "SBC will be connected to GPGPU through PCIe",
    "Rugged construction to meet MIL standards",
    "USB/Ethernet/RS232/RS485 connectivity",
    "Connector for external display interface",
    "Connector for external Ex-Rx_ALNS",
  ],
  featureList_RCA2: [
    "Durability with strong materials like steel or aluminum for protection in tough conditions",
    "Shock absorption through dampening mechanisms to safeguard electronics during transport",
    "Portability with wheels or casters and handles for easy movement",
    "Modular design for customization based on equipment size and type",
    "Cooling systems with built-in ventilation or cooling fans for optimal operating temperature",
    "Sealing and security against water, dust, and environmental hazards with locking mechanisms",
  ],
  // ---------------RugDisplaySolution-------------
  featureList_RDS1: [
    "High-resolution display with options for 15 and 24 sizes",
    "featuring 1024 x 768 or 1920 x 1080 resolution",
    "Brightness up to 1000 Nits for clear visibility in various lighting conditions",
    "Compliant with MIL-STD 810G for shock and vibration resistance",
    "MIL-STD 461E for electromagnetic interference protection",
    "Front and rear IP65 rated for dust and water resistance",
    "Rugged aluminum housing with a fanless design for efficient cooling",
    "Multiple mounting options including rack mount and VESA mount for flexible installation",
    "Military-grade power connector (MIL-DTL-38999) for secure connections",
    "Wide voltage input support from AC 230VAC to DC 9-36V, ±10%",
    "Extensive I/O connectivity including HDMI, USB, and COM ports",
    "Optional touchscreen available with capacitive or resistive technology",
    "Operating temperature range from -30°C to +70°C for reliable performance in extreme conditions",
    "Convenient on-screen display controls for easy navigation and settings adjustment",
  ],
  featureList_RDS2: [
    "Equipped with a die-cast aluminum alloy molding for durability and heat dissipation",
    "Features a fanless design for silent operation and increased reliability",
    "Onboard Intel Whiskey Lake U Series Processor delivers high performance",
    "Supports wide voltage input from 9V to 36V for versatile power options",
    "Includes TPM 2.0 security encryption for enhanced data protection",
    "Supports 2x RS232/422/485 COM ports, with an option to expand to 6",
    "Provides GPS and Glonass support for accurate positioning",
    "Offers 2x Intel LAN connections, with an option for 4 for enhanced networking",
    "IP65 rated front panel ensures protection against dust and water ingress",
    "Utilizes a military-grade power connector (MIL-DTL-38999) for secure connections",
  ],
  featureList_RDS3: [
    "Supports Intel Celeron, Intel Atom, and Intel Core i5 6360U processors for versatile performance",
    "Very low power consumption designed for energy efficiency in industrial applications",
    "Fanless design with efficient aluminum fin heat dissipation for silent operation",
    "Flat panel design with projected capacitive touch and optional tempered glass for durability",
    "IP65 rated for dust and waterproof protection, suitable for demanding environments",
    "Robust aluminum frame with rugged construction for industrial and military use",
    "High-brightness display with a resolution of 1024x768 and 250 cd/㎡ for clear visibility",
    "Extensive I/O connectivity including HDMI, USB ports, and COM ports for flexible integration",
    "Lightweight design at only 1.65 kg, allowing for easy installation and mounting options",
    "Wide operating temperature range from -30°C to +70°C ensures reliable performance in various conditions",
  ],
  // -------------panel pc ------------
  featureList_PPC1: [
    "Supports Intel Celeron & Intel Atom Processor",
    "Very low power consumption",
    "Fanless design",
    "Flat panel design with projected capacitive touch",
    "IP65 front panel waterproof protection",
    "Compact size",
    "Customized offering",
    "Mil-grade waterproof circular connectors",
    "Able to operate in temperatures between -20°C - 55°C",
  ],
  featureList_PPC2: [
    "CE certified and IP65 rated for protection against dust and water",
    "Robust aluminum frame with 15mm rugged construction for industrial and military use",
    "High-brightness display ensures clear visibility in various conditions",
    "Optional touchscreen with tempered glass for added durability and easy mounting",
    "Designed for low power consumption, promoting energy efficiency in industrial applications",
    "Supports multiple mounting options including embedded, panel, rack, and VESA mounts",
    "Wide operating temperature range, functioning between -30°C to +70°C",
    "Extensive I/O connectivity with HDMI, USB, COM ports, and Gigabit LAN",
    "Lightweight design at only 1.65 kg for easy installation",
    "Shock and vibration resistance compliant with MIL-STD-810G standards",
  ],
  featureList_PPC3: [
    "Powerful Processor Intel Core i5 6360U (Dual core, 2.0 GHz, Turbo up to 3.1 GHz)",
    "Ample Memory Equipped with 8 GB RAM for efficient multitasking",
    "High-Speed Storage 512 GB SSD ensures fast data access and storage",
    "Flexible Connectivity Optional WiFi and 3/4G module for wireless communication",
    "Multiple I/O Ports 1x HDMI, 2x USB 2.0, 2x USB 3.0, and 2x COM ports (RS232/RS485)",
    "Audio Output 1x 3.5mm audio jack for sound connectivity",
    "Vibrant Display 15-inch LCD screen with LED backlight and a resolution of 1024x768",
    "High Brightness 250 cd/㎡ for clear visibility in various lighting conditions",
    "Durable Construction Aluminum front and back cover with a glass frame for added strength",
    "Fanless Design Efficient aluminum fin heat dissipation for silent operation",
    "Multi-Touch Capabilities Capacitive touchscreen with response time exceeding 5000 touches",
    "Versatile Installation Options Supports embedded and wall mounting configurations",
  ],

  // -------rug-monitor------------
  featureList_Monitor1: [
    '15" display',
    "1024 x 768 resolution",
    "1000 Nits brightness",
    "Compliant with MIL-STD 810G/MIL-STD 461E",
    "Front & Rear IP65 rating",
    "Rack mount mechanical design, supports VESA mount",
    "Military-grade power connector (MIL-DTL-38999)",
    "AC 230VAC, optional DC 9-36V, ±10%",
    "Convenient on-screen display controls",
    "Video Input: 1 X HDMI, 1 X DP",
  ],
  featureList_Monitor2: [
    "Die cast aluminium alloy moulding",
    "Fanless design",
    "Onboard Intel Whiskey Lake U Series Processor",
    "Supports 9V ~ 36V wide voltage input",
    "TPM2.0 security encryption",
    "Support 2*RS232/422/485 COM",
    "6*COM Optional",
    "Support GPS, Glonass for more accurate positioning",
    "Support 2*Intel LANs",
    "4*Intel LANs Optional",
    "IP65 full flat front panel",
    "Applied OS",
  ],
  //---------------dual-------------
  featureList_DMC1: [
    `Ruggedized Design built to withstand extreme environments \n
     with MIL-STD compliance protecting against shock, \n
      vibration, and extreme temperatures`,
    `High-Resolution Displays providing crystal-clear \n
    visuals for precise monitoring and analysis in real-time`,
    `Multitasking Efficiency with dual monitor setup /n
     enhancing productivity allowing operators to manage multiple tasks \n
     simultaneously in command centers, control rooms, and field operations`,
    `Ergonomic and Customizable design ensuring comfort during extended \n
     use with customizable configurations for joystick control and software integration`,
    `Rugged Connectivity with advanced options supporting seamless integration \n
    with existing systems ensuring compatibility with defence, aerospace, and naval equipment`,
  ],
  featureList_DMC2: [
    `Ruggedized Design built to withstand extreme environments \n
     with MIL-STD compliance protecting against shock, \n
      vibration, and extreme temperatures`,
    `High-Resolution Displays providing crystal-clear \n
    visuals for precise monitoring and analysis in real-time`,
    `Multitasking Efficiency with dual monitor setup /n
     enhancing productivity allowing operators to manage multiple tasks \n
     simultaneously in command centers, control rooms, and field operations`,
    `Ergonomic and Customizable design ensuring comfort during extended \n
     use with customizable configurations for joystick control and software integration`,
    `Rugged Connectivity with advanced options supporting seamless integration \n
    with existing systems ensuring compatibility with defence, aerospace, and naval equipment`,
  ],
  featureList_DMC3: [
    `Ruggedized Design built to withstand extreme environments \n
     with MIL-STD compliance protecting against shock, \n
      vibration, and extreme temperatures`,
    `High-Resolution Displays providing crystal-clear \n
    visuals for precise monitoring and analysis in real-time`,
    `Multitasking Efficiency with dual monitor setup /n
     enhancing productivity allowing operators to manage multiple tasks \n
     simultaneously in command centers, control rooms, and field operations`,
    `Ergonomic and Customizable design ensuring comfort during extended \n
     use with customizable configurations for joystick control and software integration`,
    `Rugged Connectivity with advanced options supporting seamless integration \n
    with existing systems ensuring compatibility with defence, aerospace, and naval equipment`,
  ],
  // ---------------server and worksation--------
  // featureList_SW1: [
  //   '15" screen size',
  //   "1024 x 768 resolution",
  //   "1000 Nits brightness",
  //   "Compliant with MIL-STD 810G/MIL-STD 461E",
  //   "Front & Rear IP65",
  //   "Rack mount mechanical design, supports VESA mount",
  //   "Military-grade power connector (MIL-DTL-38999)",
  //   "AC 230VAC optional DC 9-36V, ±10% ±10%",
  //   "Convenient on-screen display controls",
  //   "Video Input: 1 X HDMI, 1 X DP",
  // ],
  featureList_SW2: [
    '15" screen size',
    "1024 x 768 resolution",
    "1000 Nits brightness",
    "Compliant with MIL-STD 810G/MIL-STD 461E",
    "Front & Rear IP65",
    "Rack mount mechanical design, supports VESA mount",
    "Military-grade power connector (MIL-DTL-38999)",
    "AC 230VAC optional DC 9-36V, ±10% ±10%",
    "Convenient on-screen display controls",
    "Video Input: 1 X HDMI, 1 X DP",
  ],
  featureList_SW3: [
    `Ruggedized Design built to withstand extreme environments \n
     with MIL-STD compliance protecting against shock, \n
      vibration, and extreme temperatures`,
    `High-Resolution Displays providing crystal-clear \n
    visuals for precise monitoring and analysis in real-time`,
    `Multitasking Efficiency with dual monitor setup /n
     enhancing productivity allowing operators to manage multiple tasks \n
     simultaneously in command centers, control rooms, and field operations`,
    `Ergonomic and Customizable design ensuring comfort during extended \n
     use with customizable configurations for joystick control and software integration`,
    `Rugged Connectivity with advanced options supporting seamless integration \n
    with existing systems ensuring compatibility with defence, aerospace, and naval equipment`,
  ],
  // -----------worksation------------
  featureList_W1: [
    `Ruggedized Design built to withstand extreme environments \n
     with MIL-STD compliance protecting against shock, \n
      vibration, and extreme temperatures`,
    `High-Resolution Displays providing crystal-clear \n
    visuals for precise monitoring and analysis in real-time`,
    `Multitasking Efficiency with dual monitor setup /n
     enhancing productivity allowing operators to manage multiple tasks \n
     simultaneously in command centers, control rooms, and field operations`,
    `Ergonomic and Customizable design ensuring comfort during extended \n
     use with customizable configurations for joystick control and software integration`,
    `Rugged Connectivity with advanced options supporting seamless integration \n
    with existing systems ensuring compatibility with defence, aerospace, and naval equipment`,
  ],
  //--------rugged pc tablet and box pc-------------
  featureList_RPC1: [
    "Unique IP-65 protection and cooling conception by roda",
    "Intel Celeron 2.8GHz Quad Core Processor",
    "Windows 10, Optional Windows 11 OS",
    "12.2-inch IPS Display, 650 Nit Brightness",
    "Dual-mode 5G Network (SA+NSA)",
    "Hot-Swappable Dual Batteries",
    "Support fast charge, fully charged in 3 hours",
    "EMC Electrostatic Protection",
    "Multiple Interface, Rich Accessories",
  ],
  featureList_RPC2: [
    `Support for Android 10 system`,
    `Optional 3G/4G all network communication, Wi-Fi, Bluetooth and other communication modes`,
    `10000mAh battery, 10 hours of machine endurance`,
    `IP65 high protection level, in accordance with MIL-STD-810G`,
    `Support GPS for more accurate positioning`,
    `Rear 13 million pixel auto focus camera, easy to collect image and video information`,
  ],
  featureList_RPC3: [
    "Intel® Celeron® Processor J1900, 2M Cache, up to 2.42 GHz",
    "Support -30~60°C operation temperature",
    "Support up to 8 GB RAM and 512 GB SSD",
    "Input power AC 230VAC±10%, optional 12V to VDC",
    "3 x USB 2.0, 3 x RS232, 2 x LAN (1Gbps)",
  ],
  // -----------rugged loptop---------
  featureList_Loptop1: [
    `These laptops are characterised by their unique IP-65 protection `,
    ` Cooling conception only reached by roda`,
    "Intel Celeron 2.8GHz Quad Core Processor",
    "Windows 10, optional Windows 11 OS",
    "12.2-inch IPS display, 650 Nit brightness",
    "Dual-mode 5G network (SA+NSA)",
    "Hot-swappable dual batteries",
    "Support fast charge, fully charged in 3 hours",
    "EMC electrostatic protection",
    "Multiple interface, rich accessories",
    "High-performance Intel Celeron 2.8GHz Quad Core for multitasking",
    "12.2-inch IPS Full HD display with 1920x1200 resolution and 650 Nit brightness",
    "MIL-STD-810G and IP65 design for durability against drops and hazards",
    "Hot-swappable 6300mAh dual battery for around 9 hours of use",
    "Dual-band Wi-Fi, Bluetooth 5.0, optional 5G, and multiple USB ports",
    "Operates in extreme temperatures from -20°C to 60°C and stores from -30°C to 70°C",
  ],
  featureList_Loptop2: [
    "12.2-inch IPS Full HD display with 1920x1200 resolution and 280 Nit brightness",
    "Qualcomm 2.0GHz Octa-core processor for efficient performance",
    "4GB RAM and 64GB ROM for ample storage",
    "Removable 12600mAh battery providing around 8 hours of use",
    "MIL-STD-810G and IP65 rugged design for durability in tough environments",
    "Dual-band Wi-Fi, Bluetooth 4.2, and 4G connectivity options",
    "Built-in NFC and optional barcode scanner",
    "Multiple USB ports including USB 2.0, USB 3.0, and Type-C",
    "Operates in extreme temperatures from -20°C to 60°C and stores from -30°C to 70°C",
    "GNSS support including GPS, GLONASS, and Beidou",
  ],
  featureList_Loptop3: [
    "Powered by Intel Core i5/i7 processors for strong performance",
    "13.3-inch rugged notebook with FHD resolution of 1920x1080 and 400 Nit brightness",
    "Hot-swappable dual battery system with 2800mAh capacity for extended use",
    "Supports Wi-Fi 6 and Bluetooth 5.1 for fast connectivity",
    "IP65 protection grade for resistance against dust and water",
    "Features fingerprint recognition for secure boot login",
    "Lightweight design at 2100g with dimensions of 332x233x26 mm",
    "Multiple USB 3.0 ports and HDMI output for versatile connectivity",
    "Front 2.0MP webcam and dual speakers for video conferencing",
    "Certified with MIL-STD-810G and CE-NB for durability in tough environments",
  ],
  featureList_Loptop4: [
    "Equipped with 11th Generation Intel Core i5/i7 processors for powerful performance",
    "14-inch high-definition display with a resolution of 1920 x 1080 and brightness up to 750 Nit",
    "Hot-swappable dual battery system providing around 8.5 hours of usage",
    "Built-in fingerprint recognition for enhanced security",
    "MIL-STD-810G and IP65 certifications for durability against harsh conditions",
    "Dual-band Wi-Fi, Bluetooth 5.1, and optional 4G connectivity",
    "Multi-point capacitive touchscreen with scratch-resistant design",
    "Weighs 2850g with dimensions of 363.2 x 287.4 x 42.1 mm",
    "512GB SSD and 8GB RAM for ample storage and performance",
    "Multiple USB ports, HDMI output, and Ethernet for versatile connectivity",
    "Front 2.0MP webcam and dual speakers for video conferencing",
    "Supports optional modules like barcode scanners and additional OS versions",
  ],
  featureList_Loptop5: [
    "Equipped with Intel Core i5/i7 processors for robust performance",
    "15.6-inch high-definition display with 1920x1080 resolution and 750 Nit brightness",
    "Hot-swappable dual battery system providing around 6.5 hours of usage",
    "Built-in fingerprint recognition for secure access",
    "IP65 certification and MIL-STD-810G rugged design for durability in tough environments",
    "Supports Wi-Fi 6 and Bluetooth 5.1 for advanced connectivity",
    "Multiple USB ports, HDMI output, and dual RJ45 ports for versatile connections",
    "Front 2.0MP webcam with dual speakers and digital microphones for video conferencing",
    "Optional 5G connectivity and SSD upgrades available for enhanced performance",
  ],

  // -----------rugged tablets---------
  featureList_Tablet1: [
    "Runs on Android 10 with support for 3G/4G, Wi-Fi, and Bluetooth communication",
    "Features a robust 10,000mAh battery offering up to 10 hours of endurance",
    "IP65 certification and MIL-STD-810G compliance for rugged durability",
    "10.1-inch IPS display with 1200x1920 resolution and 700 Nit brightness",
    "Equipped with a rear 13MP autofocus camera and a front 5MP camera for image and video capture",
    "ARM octa-core CPU operating at 2.0GHz with 4GB RAM and 64GB ROM",
    "Multiple I/O options including USB 3.0, USB Type-C, HDMI, and RJ45 for versatile connectivity",
    "GNSS support with GPS and Glonass for accurate positioning",
    "Operating temperature range from -20°C to 60°C and storage temperature from -30°C to 70°C",
  ],
  featureList_Tablet2: [
    "Supports Windows 10 and 11 with optional 3G/4G, Wi-Fi, and Bluetooth connectivity",
    "Equipped with a 6300mAh removable battery offering up to 8.5 hours of usage",
    "IP65 and MIL-STD-810G certified for rugged durability in harsh environments",
    "12.2-inch IPS display with a resolution of 1200x1920 and 700 Nit brightness",
    "Features front 5MP and rear 8MP autofocus cameras for capturing images and videos",
    "Powered by an Intel Jasper Lake N5100 processor with 4 cores and a maximum frequency of 2.8GHz",
    "Dual-band Wi-Fi support with Bluetooth 5.0 for reliable wireless communication",
    "Operating temperature range from -20°C to 60°C and storage temperature from -30°C to 70°C",
  ],
  featureList_Tablet3: [
    "Runs Windows 10 OS powered by an Intel Atom 1.92GHz Quad-Core processor",
    "Equipped with an 8500mAh battery providing around 8 hours of usage",
    "8-inch IPS display with resolutions of 1280x800 or 1920x1200 and up to 550 Nit brightness",
    "Offers 4GB RAM and 64GB ROM, with optional 128GB storage",
    "IP67 and MIL-STD-810G certified for rugged durability against water and dust",
    "Dual cameras featuring a 2MP front and 5MP rear for versatile imaging",
    "Communication options include Wi-Fi 5, Bluetooth 4.2, and optional 4G connectivity",
    "Designed for use in demanding environments with a drop resistance of up to 1.2 meters",
  ],
  featureList_Tablet4: [
    "Powered by a Qualcomm Snapdragon octa-core processor for smooth performance",
    "Runs on Android 10 OS for a user-friendly experience",
    "Equipped with an 8500mAh battery offering around 8 hours of usage",
    "Offers 4GB RAM and 64GB storage, expandable for increased capacity",
    "Features a vibrant 8-inch IPS display with Gorilla Glass for durability",
    "Front 5MP and rear 13MP cameras for versatile imaging capabilities",
    "IP67-rated for protection against dust and water, ensuring reliability in tough conditions",
    "Supports Wi-Fi 5, Bluetooth 4.2, and optional 4G for comprehensive connectivity",
    "Robust design compliant with MIL-STD-810G standards for drop resistance",
    "Includes various accessories like a docking charger and multiple straps for enhanced portability",
  ],
  featureList_Tablet5: [
    "Powered by a Qualcomm Snapdragon octa-core processor for efficient performance",
    "Runs on the latest Android 11 OS, offering a modern user interface",
    "Features an 8500mAh battery, providing around 8 hours of operation",
    "Supports WiFi 5, Bluetooth 4.2, and optional 5G connectivity for versatile networking",
    "Equipped with a front 5MP and rear 13MP camera for high-quality imaging",
    "Optional professional 1D/2D scanner for enhanced data collection capabilities",
    "IP67 rated for high protection against dust and water, ensuring durability in harsh environments",
    "Comes with a robust 8-inch IPS display, featuring Gorilla Glass for added strength",
    "RAM options of 4GB or 6GB and storage options of 64GB or 128GB for flexible configurations",
    "Compliant with MIL-STD-810G standards for drop resistance, making it suitable for rugged use",
  ],
  // -----------rugged Box pc---------
  featureList_Box1: [
    "Intel® Celeron® Processor J1900, 2M Cache, up to 2.42 GHz",
    "Support -30~60°C operation temperature",
    "Support up to 8 GB RAM and 512 GB SSD",
    "Input power AC 230VAC±10%, optional 12V to VDC",
    "3 x USB 2.0, 3 x RS232, 2 x LAN (1Gbps)",
  ],
};
